data:
  data_layer: data.py#CharCNNDataLayer
  init_params:
    vocab: "data/tokens.txt"
    labels_vocab: ["Fake",  "Real"]
    unk_id: 0
    max_len: 1014
  train:
    features_source: "data/train_X.txt"
    labels_source: "data/train_Y.txt"
  dev:
    features_source: "data/test_X.txt"
    labels_source: "data/test_Y.txt"  

  others:
    padding: false 